# coding: utf8
"""Custom Errors for Haystack"""

from typing import Optional
from jsonschema.exceptions import ValidationError


class HaystackError(Exception):
    """
    Any error generated by Haystack.

    This error wraps its source transparently in such a way that its attributes
    can be accessed directly: if the original error has a `message` attribute,
    `HaystackError.message` will exist and have the expected content.

    Give the source error as the `source` parameter to enable this behavior.
    Subclasses of HaystackError might enforce specific error classes as their source.
    """

    def __init__(self, message: str = "", source: Optional[Exception] = None, docs_link: Optional[str] = None):
        super().__init__()
        self.message = message
        self.source = source
        self.docs_link = None

    def __getattr__(self, attr):
        if self.source:
            return getattr(self.source, attr)

    def __str__(self):
        docs_message = f"\n\nCheck out the documentation at {self.docs_link}" if self.docs_link else ""
        if self.message and self.source:
            return f"{self.message} ({str(self.source)}){docs_message}"
        if not self.source:
            return f"{self.message}{docs_message}"
        else:
            return f"{str(self.source)}{docs_message}"


class PipelineError(HaystackError):
    """Exception for issues raised within a pipeline"""

    def __init__(
        self,
        message: str = "",
        source: Optional[Exception] = None,
        docs_link: Optional[str] = "https://haystack.deepset.ai/pipelines",
    ):
        super().__init__(message=message, source=source, docs_link=docs_link)


class PipelineConfigError(PipelineError):
    """Exception for issues raised within a pipeline's config file"""

    def __init__(self, message: str = "", source: Optional[Exception] = None, docs_link: Optional[str] = None):
        super().__init__(message=message, source=source, docs_link=docs_link)


class PipelineValidationError(PipelineError):
    """
    Exception for issues that occur while loading a pipeline

    `PipelineValidationError` is quite informative, as it
    wraps a `jsonschema.exceptions.ValidationError`.
    See [https://python-jsonschema.readthedocs.io/en/latest/errors/]
    for details about the information it carries.
    """

    def __init__(
        self,
        message: str = "",
        source: Optional[Exception] = None,
        docs_link: Optional[str] = "https://haystack.deepset.ai/pipelines#yaml-file-definitions",
    ):
        super().__init__(message=message, source=source, docs_link=docs_link)


class DocumentStoreError(HaystackError):
    """Exception for issues that occur in a document store"""

    pass


class DuplicateDocumentError(DocumentStoreError, ValueError):
    """Exception for Duplicate document"""

    pass
